### ISSUE TITLE
invalid JavaScript event names should give compiling errors

### ISSUE THREAD

**Issue by Zhen-hao** [fomkin/korolev#301]
this is just an improvement point.
currently `button("Login", event("login")` won't give compiling error. 
It will help beginners a lot if invalid JavaScript event names such as "login" give compiling errors.

I don't think Scala 2.13 has enum types. Can we use singleton types to make the event interface type-safe?

**Comment by fomkin** [comment]
Korolev should support Scala 2.12 in few next years, so it can't singleton types. Any sort of emuns is not solution too because event names is an open set: user can define custom event types as well as custom tags or attributes. I think obvious solution is `EventDef` type with standard instances in `levsha.dsl.html` package.

**Comment by Zhen-hao** [comment]
sounds good. sorry that I am not familiar with `EventDef` yet.

**Comment by fomkin** [comment]
@Zhen-hao It will be new type similar to `TagDef` or `AttrDef` from `levsha.dsl` package.
