### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by Zhen-hao** [fomkin/korolev#316]
Is there a plan of upgrade when Scala 3 is out?
Does it make sense to start developing against dotty?
I'm interested in contributing. Maybe others as well.

**Comment by fomkin** [comment]
I don't see any obstacles to use Korolev in Scala 3 (if trust compiler team [that 2.13 code will be binary compatible with Scala 3](https://github.com/lampepfl/dotty-example-project/blob/06440b20dcbe0b79dba89d44b947137eb43e1f41/README.md)). However I did not try. Levsha optimizer will not work in Scala 3 because of removing of current macros system, so optimizer should be fully rewritten with [new metaprogramming system](https://dotty.epfl.ch/docs/reference/metaprogramming/macros.html). Without optimization Levsha templates works slowly, but it's OK for experiments (I think no one consider Scala 3 for production now).

I'll not to start any activity on Scala 3 until release. Few months ago I tried to use Dotty, and it was unstable, so start porting now is losing of time IMHO.
